### PR TITLE
browserify@^11.2.0

### PR DESCRIPTION
**Pull request by KenanY**
Probably too many improvements to list :D

### CODE REVIEW

**Comment by KenanY** [comment]
@soldair Wait do we even use `browserify` anywhere? :smile:

**Comment by soldair** [comment]
i build a bundle prepublish last time i checked

**Comment by soldair** [comment]
haha yeah i guess i dont. i should use it in a test to make sure it builds the bundle correctly though

**Comment by soldair** [comment]
oh well publish 0.1.6

**Pull request merged**
